# Generated by Django 6.0.3 on 2026-03-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('release_year', models.PositiveIntegerField(verbose_name='Год выпуска')),
                ('duration', models.PositiveIntegerField(verbose_name='Длительность (мин)')),
                ('genre', models.CharField(max_length=100, verbose_name='Жанр')),
                ('poster', models.CharField(max_length=255, verbose_name='Постер')),
            ],
        ),
    ]
